# Generated by Django 4.2 on 2023-05-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(
                default="default-img.jpeg", upload_to="image/$Y", verbose_name="Image"
            ),
            preserve_default=False,
        ),
    ]
