# Generated by Django 4.2 on 2023-05-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(upload_to="image/%Y", verbose_name="Image"),
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=50, verbose_name="IP")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                        verbose_name="post",
                    ),
                ),
            ],
        ),
    ]
